### ISSUE TITLE
Resolver problema "Error al obtener las rutas disponibles: Paquete is not associated to AsignacionPaquete!"

### ISSUE THREAD

**Issue by Gironmv12** [Gironmv12/Fletex#8]
resolver el siguiente problema:
`!Error al obtener las rutas disponibles: Paquete is not associated to AsignacionPaquete!"`

```
Detalles del error: EagerLoadingError [SequelizeEagerLoadingError]: Paquete is not associated to AsignacionPaquete!
    at AsignacionPaquete._getIncludedAssociation (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:565:13)
    at AsignacionPaquete._validateIncludedElement (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:502:53)
    at C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:421:37
    at Array.map (<anonymous>)
    at AsignacionPaquete._validateIncludedElements (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:417:39)
    at Ruta._validateIncludedElement (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:557:38)
    at C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:421:37
    at Array.map (<anonymous>)
    at Ruta._validateIncludedElements (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:417:39)
    at Ruta.findAll (C:\Users\Giron\Desktop\Fletex\backend\node_modules\sequelize\lib\model.js:1124:12)
Error en la carga ansiosa (Eager loading): Verifica las asociaciones
```

**Comment by Gironmv12** [comment]
Terminado y problema resuelto

```
// Obtener rutas disponibles
router.get('/getRutasDisponibles', async (_, res) => {
    try {
        const rutas = await sequelize.query('CALL obtener_rutas_disponibles()', {
            type: Sequelize.QueryTypes.RAW
        });

        res.json(rutas);
    } catch (error) {
        console.error('Error al obtener las rutas disponibles:', error.message);
        console.error('Detalles del error:', error);

        res.status(500).json({
            error: 'Error al obtener las rutas disponibles',
            message: error.message,
            stack: error.stack
        });
    }
});
```
